### ISSUE TITLE
Got invalid dimensions for input: past_key_values.1.decoder.key for the following indices  index: 3 Got: 85 Expected: 64 (exporting google/mt5-small)

### ISSUE THREAD

**Issue by xenova** [huggingface/optimum#1004] opened 2023-04-21 23:57 UTC
### System Info

```shell
optimum: 1.8.3.dev0 (latest commit)
transformers: 4.28.1
OS: Windows 10
Python: 3.8.3
```

### Who can help?

@michaelbenayoun @fxmarty

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Running the following command will throw the error:
```
optimum-cli export onnx -m google/mt5-small output
```

error:
```
│ ...\Python\Python38\lib\site-packages\optimum\exporters\onnx\_ │
│ _main__.py:360 in main_export                                                                    │
│                                                                                                  │
│   357 │   │   │   │   f"The ONNX export succeeded with the warning: {e}.\n The exported model    │
│   358 │   │   │   )                                                                              │
│   359 │   │   except Exception as e:                                                             │
│ ❱ 360 │   │   │   raise Exception(                                                               │
│   361 │   │   │   │   f"An error occured during validation, but the model was saved nonetheles   │
│   362 │   │   │   )                                                                              │
│   363                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
Exception: An error occured during validation, but the model was saved nonetheless at output. Detailed error: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input:
past_key_values.1.decoder.key for the following indices
 index: 3 Got: 85 Expected: 64
 Please fix either the inputs or the model..
```

### Expected behavior

The model should export correctly.

**Comment by fxmarty** [comment] 2023-04-23 13:36
Hi @xenova, this should be fixed in #1007 . The issue is that mt5-small does not respect the constraint d_kv = d_model // num_heads (see https://huggingface.co/t5-small/blob/main/config.json)

**Closed** 2023-04-23 14:29 UTC
Labels: bug
