### ISSUE TITLE
Model Loading Error

### ISSUE THREAD

**Issue by jafri** [huggingface/optimum#440] opened 2022-10-29 12:36 UTC
### System Info

```shell
Running latest versions of optimum and transformers.

Running following code from [docs](https://huggingface.co/docs/optimum/onnxruntime/usage_guides/models#export-and-inference-of-sequencetosequence-models): 

Get error:


Traceback (most recent call last):
  File "/Users/sid/Personal/sid/src/d.py", line 5, in <module>
    model = ORTModelForSeq2SeqLM.from_pretrained("t5-base", from_transformers=True)
  File "/Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages/optimum/onnxruntime/modeling_ort.py", line 252, in from_pretrained
    return super().from_pretrained(
  File "/Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages/optimum/modeling_base.py", line 232, in from_pretrained
    return cls._from_transformers(
  File "/Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages/optimum/onnxruntime/modeling_seq2seq.py", line 453, in _from_transformers
    export(
  File "/Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages/transformers/onnx/convert.py", line 339, in export
    return export_pytorch(preprocessor, model, config, opset, output, tokenizer=tokenizer, device=device)
  File "/Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages/transformers/onnx/convert.py", line 163, in export_pytorch
    onnx_export(
  File "/Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages/torch/onnx/utils.py", line 497, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages/torch/onnx/utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages/torch/onnx/__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages/torch/onnx/utils.py", line 1032, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages/torch/onnx/symbolic_opset9.py", line 1831, in full_like
    value_t=torch.tensor([fill_value], dtype=sym_help.scalar_type_to_pytorch_type[dtype]))
TypeError: 'float' object cannot be interpreted as an integer 
(Occurred when translating full_like).
```
```


### Who can help?

@lewtun @micha

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import AutoTokenizer, pipeline
from optimum.onnxruntime import ORTModelForSeq2SeqLM
model = ORTModelForSeq2SeqLM.from_pretrained("t5-base", from_transformers=True)
```

### Expected behavior

Load model from transformers without error

**Comment by regisss** [comment] 2022-10-29 17:12
@jafri On my laptop with Optimum 1.4.1, Transformers 4.23.1 and PyTorch 1.12.0 it runs without any error.
Which version of PyTorch and ONNX did you use to run this example? You can get them with the following command: `pip show torch onnx`.

**Comment by jafri** [comment] 2022-10-29 17:13
Name: torch
Version: 1.10.2
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages
Requires: typing_extensions
Required-by: optimum
---
Name: onnx
Version: 1.12.0
Summary: Open Neural Network Exchange
Home-page: https://github.com/onnx/onnx
Author: ONNX
Author-email: onnx-technical-discuss@lists.lfaidata.foundation
License: Apache License v2.0
Location: /Users/sid/opt/anaconda3/envs/sid/lib/python3.10/site-packages
Requires: protobuf, typing-extensions, numpy
Required-by:

**Comment by jafri** [comment] 2022-10-29 17:15
On M1 mac, note that the following code works

```
from transformers import AutoTokenizer, pipeline
from optimum.onnxruntime import ORTModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("optimum/t5-small")
model = ORTModelForSeq2SeqLM.from_pretrained("optimum/t5-small")
```

**Comment by regisss** [comment] 2022-10-29 17:36
`"optimum/t5-small"` is an ONNX model so no conversion is needed. Because the error you reported happened during the conversion to the ONNX format.

I cannot reproduce this error at the moment, I will try on a M1.

**Comment by jafri** [comment] 2022-10-29 17:42
Weirdly enough, I was also able to solve the issue by using python 3.10 not inside anaconda

**Comment by regisss** [comment] 2022-10-29 17:48
That's weird indeed. I'm glad you managed to solve it!
Shall I close this issue?

**Closed** 2022-10-29 17:49 UTC
Labels: bug
