### ISSUE TITLE
convert llama-7B Failed to allocate memory for requested buffer of size 90177536

### ISSUE THREAD

**Issue by nkjulia** [huggingface/optimum#1060] opened 2023-05-18 02:12 UTC
### System Info

```shell
v100 2*C
transformers             4.30.0.dev0
optimum                  1.8.5
onnx                     1.13.1
onnxruntime              1.14.1
onnxruntime-gpu          1.14.1

optimum-cli export onnx --model /data/yahma-llama-7b-hf/ --task causal-lm-with-past --fp16 --for-ort --device cuda llama-onnx

============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Saving external data to one file...
2023-05-18 09:46:47.397498088 [W:onnxruntime:, session_state.cc:1136 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-05-18 09:46:47.397535341 [W:onnxruntime:, session_state.cc:1138 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2023-05-18 09:46:49.687956512 [E:onnxruntime:, inference_session.cc:1532 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:368 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool, onnxruntime::Stream*, bool, onnxruntime::WaitNotificationFn) Failed to allocate memory for requested buffer of size 90177536
```

### Who can help?

@michaelbenayoun

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

optimum-cli export onnx --model /data/yahma-llama-7b-hf/ --task causal-lm-with-past --fp16 --for-ort --device cuda llama-onnx

### Expected behavior

convert llama to onnx successfuly

**Comment by xenova** [comment] 2023-05-20 13:57
How much RAM do you have? May be related to https://github.com/huggingface/optimum/issues/1012

**Comment by nkjulia** [comment] 2023-05-22 08:41
> How much RAM do you have? May be related to #1012

77G in total

**Comment by michaelbenayoun** [comment] 2023-05-24 08:35
Hi @nkjulia,
Are you able to perform the export without the `--fp16` flag?

**Comment by nkjulia** [comment] 2023-05-26 06:11
> Hi @nkjulia, Are you able to perform the export without the `--fp16` flag?

failed still.

uple(x.clone(memory_format=torch.preserve_format) for x in args)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 31.75 GiB total capacity; 30.99 GiB already allocated; 48.75 MiB free; 30.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by thedogb** [comment] 2023-06-13 09:03
same here.
and i fix it by  --no-post-process 

```bash
optimum-cli export onnx --task 'causal-lm-with-past' --model ./llama-7b --no-post-process  llama-7b-onnx 
```

i run it in cpu mode with 80g memory. you can try it in your  case.

**Comment by michaelbenayoun** [comment] 2023-06-14 08:36
We might need to work to make the post processing step lighter. Thanks for figuring this out @thedogb

**Comment by Fire-Hound** [comment] 2023-06-14 23:43
I am facing the same problem of oom on a 80gb A100. 
What's the relevance of post-processing? Will it affect how the model is exported? @michaelbenayoun 
Sorry I am new to onnx and trying to figure stuff out.

**Comment by fxmarty** [comment] 2023-06-15 06:27
@Fire-Hound What error do you get? Could you copy the traceback/log? A simple `Killed` or an OOM? I can not reproduce on A100-80GB, `CUDA_VISIBLE_DEVICES=0 optimum-cli export onnx --model huggingface/llama-7b --fp16 --device cuda llama_7b_onnx` runs fine on optimum main + ort 1.15.0 + pytorch 2.0.1.

**Comment by fxmarty** [comment] 2023-06-15 06:52
What I find is that, for llama-7b with `CUDA_VISIBLE_DEVICES=0 optimum-cli export onnx --model huggingface/llama-7b --fp16 --device cuda llama_7b_onnx`:

The export itself uses at most 20 GiB RAM, 45 GiB GPU memory.
The post-processing uses at most 33.7 GiB RAM, which is arguably high, and has still ~28 GiB GPU memory allocated which should not maybe not be.
The validation uses at most ~62 GiB GPU RAM, which is arguably high, likely because of ORT.

**Comment by Fire-Hound** [comment] 2023-06-15 10:30
Sorry for the confusion I am trying it on a 33b model. Do you think 2xA100 80Gb will have enough VRAM for the export?

**Comment by Fire-Hound** [comment] 2023-06-15 10:34
> @Fire-Hound What error do you get? Could you copy the traceback/log? A simple `Killed` or an OOM? I can not reproduce on A100-80GB, `CUDA_VISIBLE_DEVICES=0 optimum-cli export onnx --model huggingface/llama-7b --fp16 --device cuda llama_7b_onnx` runs fine on optimum main + ort 1.15.0 + pytorch 2.0.1.
> 
> @thedogb @nkjulia If you are able to provide a log, it help as well to fix.

I can rerun it today and provide the stack trace, I get a CUDA out-of-memory exception, it's the one you get when you try to allocate more memory than what's available.

**Comment by fxmarty** [comment] 2023-06-15 12:47
Oh I see! Can you run generation in pytorch, with a small context (a few tokens), batch_size = 2, and min_new_tokens=max_new_tokens=2? If so, *maybe* the export may succeed on pytorch nightlies. llama-30b is 65 GB in fp 16, so it's already huge.

Also, I wouldn't have too high hopes to manage to run llama-30b with ONNX Runtime on CUDAExecutionProvider - which is unfortunately more memory intensive than pytorch.

**Comment by fxmarty** [comment] 2023-06-19 04:55
Closing as the GPU memory issue is a pytorch one, not optimum: https://github.com/pytorch/pytorch/pull/101134 & https://github.com/pytorch/pytorch/pull/101148

You can try to use pytorch nightly until 2.1 is released that fixes the issue. Following https://github.com/huggingface/optimum/pull/1115 https://github.com/huggingface/optimum/pull/1112 https://github.com/huggingface/optimum/pull/1111 the GPU memory usage should not exceed the one from `torch.onnx.export`, so I think there is not much more we can do on our side. We will probably do a release soon including those fixes.

The post-processing (as describe above) is run on CPU, so if GPU OOM arises, it is not at fault.

**Closed by fxmarty** 2023-06-19 04:55 UTC
Labels: bug
