### ISSUE TITLE
[Bug] tensorrt engine cannot store locally

### ISSUE THREAD

**Issue by PoodleWang** [huggingface/optimum#606] opened 2022-12-18 10:40 UTC
### System Info

```shell
Cannot store the tensorrt engine locally.
I used the PR: https://github.com/huggingface/optimum/pull/586.  I am not sure whether this bug happened on the production.
```

### Who can help?

@JingyaHuang 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```Python
model = ORTModelForCausalLM.from_pretrained(
"Salesforce/codegen-6B-mono/",
from_transformers=True,
provider="TensorrtExecutionProvider"
)
model.save_pretrained("./codegen-6B-mono-onnx")
```

above code generate the below structure:
--codegen-6B-mono-onnx
----config.json
----decoder_model.onnx
----decoder_model.onnx_data
----decoder_with_past_model.onnx
----decoder_with_past_model.onnx_data

```Python
provider_options = {
"trt_engine_cache_enable": 1,
"trt_engine_cache_path": "/opt/tiger/genius/checkpoints/codegen-6B-mono/trt",
}
model = ORTModelForCausalLM.from_pretrained(
"/opt/tiger/genius/checkpoints/codegen-6B-mono/onnx",
provider="TensorrtExecutionProvider",
provider_options = provider_options,
)
```

### Expected behavior

LOG:
2022-12-18 13:25:25.887143: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-18 13:25:26.000533: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable TF_ENABLE_ONEDNN_OPTS=0.
2022-12-18 13:25:26.510609: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/tiger/yarn_deploy/jdk/jre/lib/amd64/server:/opt/tiger/yarn_deploy/hadoop_current/lib/native:/opt/tiger/yarn_deploy/hadoop_current/lib/native/ufs:/opt/tiger/yarn_deploy/hadoop/lib/native:/opt/tiger/yarn_deploy/hadoop_current/lib/native:/opt/tiger/yarn_deploy/hadoop/lib/native:/opt/tiger/jdk/jdk1.8/jre/lib/amd64/server:/usr/local/cuda/lib64::/usr/local/cuda/compat
2022-12-18 13:25:26.510701: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/tiger/yarn_deploy/jdk/jre/lib/amd64/server:/opt/tiger/yarn_deploy/hadoop_current/lib/native:/opt/tiger/yarn_deploy/hadoop_current/lib/native/ufs:/opt/tiger/yarn_deploy/hadoop/lib/native:/opt/tiger/yarn_deploy/hadoop_current/lib/native:/opt/tiger/yarn_deploy/hadoop/lib/native:/opt/tiger/jdk/jdk1.8/jre/lib/amd64/server:/usr/local/cuda/lib64::/usr/local/cuda/compat
2022-12-18 13:25:26.510711: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
EP Error using ['TensorrtExecutionProvider', 'CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error using ['TensorrtExecutionProvider', 'CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.

**Comment by JingyaHuang** [comment] 2022-12-19 00:55
Hi @PoodleWang,

According to the log

```
2022-12-18 13:25:26.510711: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
EP Error using ['TensorrtExecutionProvider', 'CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
```  
It seems that there is an issue with your installation of TensorRT, and onnxruntime falls back to CUDA execution provider. Can you have a check of your TensorRT installation with the [steps in our doc](https://huggingface.co/docs/optimum/onnxruntime/usage_guides/gpu#tensorrtexecutionprovider)? Thx.

**Comment by PoodleWang** [comment] 2022-12-21 20:20
> Hi @PoodleWang,
> 
> According to the log
> 
> ```
> 2022-12-18 13:25:26.510711: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
> EP Error using ['TensorrtExecutionProvider', 'CUDAExecutionProvider']
> Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
> ```
> 
> It seems that there is an issue with your installation of TensorRT, and onnxruntime falls back to CUDA execution provider. Can you have a check of your TensorRT installation with the [steps in our doc](https://huggingface.co/docs/optimum/onnxruntime/usage_guides/gpu#tensorrtexecutionprovider)? Thx.


Please take a look at this PR. My tensorrt installed correctly

**Comment by fxmarty** [comment] 2022-12-22 15:11
maybe related https://neo-ai-dlr.readthedocs.io/en/latest/tensorrt.html#caching-tensorrt-engines

**Comment by fxmarty** [comment] 2022-12-29 15:14
Hi @PoodleWang , sorry you run into those issues with Optimum + TensorRT. Hopefully these issues will be fixed in the following days/weeks :)

The error you get
```
 EP Error using ['TensorrtExecutionProvider', 'CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error using ['TensorrtExecutionProvider', 'CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
```

is fixed in https://github.com/huggingface/optimum/pull/653 .

Note that you will need to pass the options:
```python
provider_options = {
    "trt_engine_cache_enable": True,
    "trt_engine_cache_path": "/opt/tiger/genius/checkpoints/codegen-6B-mono/trt",
}
```

and NOT:

```python
provider_options = {
    "trt_engine_cache_enable": 1,
    "trt_engine_cache_path": "/opt/tiger/genius/checkpoints/codegen-6B-mono/trt",
}
```

Reference: https://github.com/microsoft/onnxruntime/issues/14091

**Closed** 2023-01-02 12:41 UTC
Labels: bug

**Comment by fxmarty** [comment] 2023-01-02 12:43
Hi @PoodleWang , the issue is fixed on the main branch. Note that the documentation is improved as well regarding the TensorRT engine: https://github.com/huggingface/optimum/pull/657
