### ISSUE TITLE
BetterTransfomer Support for the GPTBigCode model

### ISSUE THREAD

**Issue by amarazad** [huggingface/optimum#1346] opened 2023-09-04 16:52 UTC
### Feature request

is it possible to support GPTBigCode with BetterTransformer?

https://huggingface.co/docs/transformers/model_doc/gpt_bigcode

### Motivation

A very popular Decoder model for Code.

### Your contribution

hope you can achieve it. Thanks.

**Comment by fxmarty** [comment] 2023-09-05 16:58
Thank you @amarazad for the notice! It is already available and was missing from our documentation, fixed with https://github.com/huggingface/optimum/pull/1356

Measuring the forward latency during generation with `CUDA_VISIBLE_DEVICES=0 python benchmark_bettertransformer.py --model-name bigcode/gpt_bigcode-santacoder --is_decoder --use-half --use-cuda --batch-size 1 --num-batches 5 --max-seqlen 500 --max_token 500` from `tests/benchmark/benchmark_bettertransformer.py`, I get:

|   num_batches |    batch_size |    seq_len |  is cuda   |  is half   |  use mask   |    pad percentage |    Latency eager (ms) |    Latency BT (ms) |    Speedup (%) |    Mem eager (MB) |    Mem BT (MB) |    Mem saved (%) |
|--------------:|--------------:|-----------:|:-----------|:-----------|:------------|------------------:|----------------------:|-------------------:|---------------:|------------------:|---------------:|-----------------:|
|             5 |             1 |        500 | True       | True       | False       |                 0 |                5985.6 |            4227.99 |         41.571 |           2392.87 |        2392.86 |            0.001 |

(which is arguably very nice.)

The speedup should be more significant during training.

**Closed** 2023-09-05 16:58 UTC

**Comment by amarazad** [comment] 2023-09-05 19:51
@fxmarty I get this warning 
`The BetterTransformer implementation does not support padding during training, as the fused kernels do not support attention masks. Beware that passing padded batched data during training may result in unexpected outputs. Please refer to https://huggingface.co/docs/optimum/bettertransformer/overview for more details.`
And the overview page states that it is not suited for finetuning task. 
How is the attention mask computed here ?
I am looking for memory efficient finetuning with attention mask set to ignore for padded tokens. Can you please confirm if BetterTransformer API is applicable for it ?

**Comment by fxmarty** [comment] 2023-09-06 08:35
@amarazad It is not as noted in the documentation. Under the hood, BetterTransformer uses pytorch torch.nn.functional.scaled_dot_product_attention whose optimized kernels (flash attention, memory-efficient attention) not support passing an arbitrary padding mask during training (and during inference as well when using non-nested tensor).

This is slightly relaxed by https://github.com/pytorch/pytorch/issues/96099, which upstreams support for memory-efficient attention with an arbitrary mask. Once PyTorch 2.1 is released, I will benchmark it and possibly provide an option in order to not drop the attention mask. But in this case, we will not be able to dispatch to flash attention anymore.

Note: in your training scenario, you may or may not be able to pack your training data in order to avoid any padding at all, see for example: https://github.com/huggingface/transformers/blob/172f42c512e1bf32554ef910fe82f07916b4d4af/examples/pytorch/language-modeling/run_clm_no_trainer.py#L456

**Comment by amarazad** [comment] 2023-09-08 13:53
@fxmarty 
I am facing some error while while reversing to save at 
`unwrapped_model= BetterTransformer.reverse(unwrapped_model._fsdp_wrapped_module)`
The BetterTransformer wraps the model fine, does memory efficient finetuning but gets stuck at reversing. 

Full error trace is:
```
Traceback (most recent call last):
  File "/server/ftdir//finetuning/finetuning.py", line 649, in <module>
    main()
  File "/server/ftdir//finetuning/finetuning.py", line 610, in main
    train_model(accelerator, model, train_dataloader, tokenizer, optimizer, lr_scheduler, config['TRAIN_CONFIG'], valid_dataloader, config['VALID_CONFIG'], config, writer, device)
  File "/server/ftdir//finetuning/finetuning.py", line 468, in train_model
    train_epoch(accelerator, model, train_dataloader, tokenizer, optimizer, lr_scheduler, train_variables_dict, train_config, valid_dataloader, valid_config, config, writer, epoch, device )
  File "/server/ftdir//finetuning/finetuning.py", line 246, in train_epoch
    save_ckpt(accelerator, config, model, tokenizer, optimizer, lr_scheduler, train_variables_dict['total_step'], epoch, flag="best")
  File "/server/ftdir//finetuning/finetuning.py", line 310, in save_ckpt
    unwrapped_model= BetterTransformer.reverse(unwrapped_model._fsdp_wrapped_module)
  File "/server/anaconda3/envs/llm/lib/python3.9/site-packages/optimum/bettertransformer/transformation.py", line 377, in reverse
    recurse_setattr(reversed_model, path, recurse_getattr(bt_model, path))
  File "/server/anaconda3/envs/llm/lib/python3.9/site-packages/optimum/utils/modeling_utils.py", line 41, in recurse_setattr
    recurse_setattr(getattr(module, name), rest, value)
  File "/server/anaconda3/envs/llm/lib/python3.9/site-packages/optimum/utils/modeling_utils.py", line 41, in recurse_setattr
    recurse_setattr(getattr(module, name), rest, value)
  File "/server/anaconda3/envs/llm/lib/python3.9/site-packages/optimum/utils/modeling_utils.py", line 38, in recurse_setattr
    setattr(module, name, value)
  File "/server/anaconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1635, in __setattr__
    raise TypeError("cannot assign '{}' as parameter '{}' "
TypeError: cannot assign 'torch.FloatTensor' as parameter 'weight' (torch.nn.Parameter or None expected)
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1265595 closing signal SIGTERM

```
I am using the follwing environment
```
transformers==4.31.0
accelerate==0.21.0
optimum
```
and `torch Version: 2.0.1` over `cuda 11.8`. 
Any leads would be helpful.

**Comment by fxmarty** [comment] 2023-09-08 14:51
@amarazad Could you open a separate issue with a reproduction? I believe the issue is related to the usage of torch.distributed, I'll have a look once I can reproduce!
