### ISSUE TITLE
MT5 Support 

### ISSUE THREAD

**Issue by MiladMolazadeh** [huggingface/optimum#321] opened 2022-07-28 09:25 UTC
Big Thanks for the awesome Optimum library, 
MT5 is a Massive Transformers And Supports Many Languages, but it has a slow inference time
for speedup MT5 inference time, We need some post-training methods, and Optimum will help more!

Please Add MT5 Support for Optimum! Thanks

**Comment by JingyaHuang** [comment] 2022-07-28 09:58
Hi @MiladMolazadeh, thanks for the suggestion! Are you interested in opening a PR to add MT5?

Basically to add the support for a new model there are __3 steps__ to follow and __2 PR__ in two repos will be needed:

__[transformers]__
------------------------
1. Add OnnxConfig in transformers -> which enables the export to ONNX format(in the case of MT5, it shall be the same as the ONNXConfig of T5). 
  * [Detailed guide on adding unsupported models](https://huggingface.co/docs/transformers/serialization#exporting-a-model-for-an-unsupported-architecture)
  * You can find more discussion [here](https://github.com/huggingface/transformers/issues/16308)
2. Register supported tasks of the model into [`transformers.onnx.FeaturesManager`](https://github.com/huggingface/transformers/blob/main/src/transformers/onnx/features.py), by far you will be able to export the model to ONNX / use `ORTModels` for inference / use `ORTQuantizer` for quantization.

__[Optimum]__
------------------------
3. If you are also interested in using `ORTOptimizer` to do some graph optimizations, then you shall open a PR in optimum to add the support of MT5 in [`ORTConfigManager`](https://github.com/huggingface/optimum/blob/main/optimum/onnxruntime/utils.py#L60)

Please feel free to reach out if have any further questions.

**Comment by ChainYo** [comment] 2022-08-01 08:24
Hi, I'm working this morning on the MT5 Onnx Config implementation. It should be added during this week! @JingyaHuang 

> Hi @MiladMolazadeh, thanks for the suggestion! Are you interested in opening a PR to add MT5?

**Comment by ChainYo** [comment] 2022-08-09 08:16
Quick update `MT5OnnxConfig` has been merged to the main branch. @MiladMolazadeh

**Comment by irg1008** [comment] 2022-09-01 10:23
Hi, greate work merging the feature on MT5 models!.

I have tried adding the key/value pair to the dict and I got the next error converting the model to Onnx:
`RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 85 but got size 64 for tensor number 1 in the list.`

It works with BART model so I don´t really know where the problem is. Any idea?

**Closed** 2022-10-02 12:05 UTC

**Comment by jhpassion0621** [comment] 2024-02-06 20:26
Hi, @MiladMolazadeh, Thanks for your adding MT5! Can you add UMT5 as well?
I fine tunned this model and I would like to export to ONNX but it doesn't support yet. I am very appreciate you to do this for me.
