### ISSUE TITLE
Unable to Export Whisper-Large-V3 Model to ONNX Format in Optimum

### ISSUE THREAD

**Issue by Harini-Vemula-2382** [huggingface/optimum#1811] opened 2024-04-12 14:21 UTC
### System Info

```shell
Optimum Version: 1.18.0
Python Version: 3.8
Platform: Windows, x86_64
```

### Who can help?

@michaelbenayoun @JingyaHuang @echarlaix

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

optimum-cli export onnx --model openai/whisper-large-v3 whisper_large_v3_optimum_onnx/ --trust-remote-code

### Expected behavior

I would expect Optimum to successfully export the Whisper-Large-V3 model to ONNX format without encountering any errors or issues.

**Comment by fxmarty** [comment] 2024-04-16 13:47
@Harini-Vemula-2382 Closing as this is fixed on the dev branch, using `torch==2.2.2`, `onnx==1.16.0`, `onnxruntime==1.17.3`. An optimum release is coming today.

As you did not share logs, my best guess is that this is fixed in https://github.com/huggingface/optimum/pull/1780.

If the issue is not resolved on optimum==1.19 could you share the full export log, as well as `pip freeze`?

**Closed** 2024-04-16 13:47 UTC
Labels: bug
